[features]
seeds = false
skip-lint = false
[programs.localnet]
dice_roll = "ERRCx3eF4vpLDNcJERAM7MRVCE9NxJxDQs7qMDo6C7aj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/fuujack/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
